name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: native
            target: ""
            features: http,jwt-simple,jwt-simple/pure-rust,moka
          - name: wasm
            target: wasm32-unknown-unknown
            features: cloudflare,http,jwt-simple,jwt-simple/pure-rust,web-crypto

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust
        uses: ./.github/actions/rust/

      - name: Install wasm target
        if: matrix.target == 'wasm32-unknown-unknown'
        run: rustup target add wasm32-unknown-unknown

      - name: Build
        run: |
          if [ -n "${{ matrix.target }}" ]; then
            cargo build --target "${{ matrix.target }}" --features "${{ matrix.features }}"
          else
            cargo build --features "${{ matrix.features }}"
          fi

  test:
    name: Test (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: native
            target: ""
            features: http,jwt-simple,jwt-simple/pure-rust,moka
          - name: wasm
            target: wasm32-unknown-unknown
            features: cloudflare,http,jwt-simple,jwt-simple/pure-rust,web-crypto

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust
        uses: ./.github/actions/rust/

      - name: Install wasm target
        if: matrix.target == 'wasm32-unknown-unknown'
        run: rustup target add wasm32-unknown-unknown

      # TODO: pinned for now to make CI green
      # needs some automation
      - name: Install wasm-bindgen test runner
        if: matrix.target == 'wasm32-unknown-unknown'
        run: cargo install -f wasm-bindgen-cli --version 0.2.108

      - name: Test
        run: |
          if [ -n "${{ matrix.target }}" ]; then
            cargo test --target "${{ matrix.target }}" --features "${{ matrix.features }}"
          else
            cargo test --features "${{ matrix.features }}"
          fi

  lint:
    name: Lint (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: native
            target: ""
            features: http,jwt-simple,jwt-simple/pure-rust,moka
          - name: wasm
            target: wasm32-unknown-unknown
            features: cloudflare,http,jwt-simple,jwt-simple/pure-rust,web-crypto

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust
        uses: ./.github/actions/rust/

      - name: Install wasm target
        if: matrix.target == 'wasm32-unknown-unknown'
        run: rustup target add wasm32-unknown-unknown

      - name: fmt
        if: matrix.target == ''
        run: cargo fmt -- --check

      - name: Clippy
        run: |
          if [ -n "${{ matrix.target }}" ]; then
            cargo clippy --target "${{ matrix.target }}" --features "${{ matrix.features }}"
          else
            cargo clippy --features "${{ matrix.features }}"
          fi

  examples:
    name: Examples (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: native
            target: ""
            features: http,jwt-simple,jwt-simple/pure-rust
          - name: wasm
            target: wasm32-unknown-unknown
            features: http,jwt-simple,jwt-simple/pure-rust,web-crypto

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust
        uses: ./.github/actions/rust/

      - name: Install wasm target
        if: matrix.target == 'wasm32-unknown-unknown'
        run: rustup target add wasm32-unknown-unknown

      - name: Check examples
        run: |
          if [ -n "${{ matrix.target }}" ]; then
            cargo check --examples --target "${{ matrix.target }}" --features "${{ matrix.features }}"
          else
            cargo check --examples --features "${{ matrix.features }}"
          fi
